name: deploy cookbot
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-ukulele:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: install server
        working-directory: ./server
        run: yarn install
      - name: Make server envfile
        uses: SpicyPizza/create-envfile@v1

        with:
          envkey_COOKBOT_BOT_TOKEN: ${{ secrets.COOKBOT_BOT_TOKEN }}
          envkey_COOKBOT_BOT_NAME: ${{ secrets.COOKBOT_BOT_NAME }}
          envkey_COOKBOT_MYSQL_USER: ${{ secrets.COOKBOT_MYSQL_USER }}
          envkey_COOKBOT_MYSQL_PW: ${{ secrets.COOKBOT_MYSQL_PW }}
          envkey_COOKBOT_MYSQL_HOST: ${{ secrets.COOKBOT_MYSQL_HOST }}
          envkey_COOKBOT_MYSQL_PORT: ${{ secrets.COOKBOT_MYSQL_PORT }}
          envkey_COOKBOT_MYSQL_DB: ${{ secrets.COOKBOT_MYSQL_DB }}
          directory: server
          file_name: .env
      - name: build server
        working-directory: ./server
        run: yarn build
      - name: restart server
        working-directory: ./server
        run: pm2 reload cookbot-server
